flowchart TD;
    
    %% Conexiones principales
    A --> B
    B --> C
    B --> D
    C --> B
    D --> B
    B --> E
    E --> F
    E --> I
    I --> G
    G --> H
    
    %% Subgrupos para mejorar estructura
    subgraph Inici
        A[Inici, Benvinguda]
    end

    subgraph Login
        B{Login<br>Usuari i contrasenya}
    end

    subgraph Registre
        C[Registre<br>Nom, Cognom, Email, Contrasenya]
    end

    subgraph RecuperarContrasenya
        D{Recuperar Contrasenya<br>Email, Codi de Recuperació}
    end

    subgraph Usuari
        E{Usuari<br>Nom, Cognom, Email}
        I{Llista de Nens<br>Nom, Edat, Data de Naixement}
        G{Informació Nen<br>Nom, Edat, Data de Naixement, Informació Mèdica}
    end

    subgraph Perfil
        F{Veure Perfil<br>Nom, Cognom, Email, Altres dades}
    end

    subgraph Nen
        H{Historial del Tapat<br>Data, Hora, Estat, Total d'hores}
    end
