flowchart TD
    A[WebService] --> B[DAOUsers] : Consulta a
    A --> C[DAOChilds] : Consulta a
    A --> D[DAOTaps] : Consulta a

    B --> E[Users] : Gestiona
    C --> F[Child] : Gestiona
    D --> G[Tap] : Gestiona
