flowchart TD
    WebService --> DAOUsers : Consulta a
    WebService --> DAOChilds : Consulta a
    WebService --> DAOTaps : Consulta a

    DAOUsers --> Users : Gestiona
    DAOChilds --> Child : Gestiona
    DAOTaps --> Tap : Gestiona
