classDiagram

    class User {
        +int id
        +String username
        +String email
        +String password
    }

    class UserDAO {
        +users
        +get_all_users(): List
        +get_user_by_username(username: String): User
    }

    class Webservice {
        +get_users(): void
        +get_user_by_username(username: String): void
    }

    UserDAO --|> User : Té una llista de
    Webservice --|> UserDAO : Consulta
