flowchart TD;
    
    %% Conexiones principales
    A --> B
    B --> C
    B --> D
    B --> E
    C --> J
    E --> I
    E --> F
    F --> K
    I --> G
    G --> H
    
    %% Pantallas
    A[Inici]
    B{Login}
    C[Registre]
    D{Recuperar Contrasenya}
    E{Usuari}
    F{Veure Perfil}
    G{Informació Nen}
    H{Historial del Tapat}
    I[Llista de Nens]
    J[Afegir Nen]
    K[Afegir Nen]
